forge 'https://forge.puppet.com'

mod 'WhatsARanjit-node_manager', '0.7.1'
mod 'danieldreier-autosign', '0.2.0'
mod 'petems-swap_file', '4.0.0'
mod 'puppet-archive', '3.2.1'
mod 'puppet-grafana', '5.0.0'
mod 'puppetlabs-apt', '6.3.0'
mod 'puppetlabs-exec', '0.3.0'
mod 'puppetlabs-inifile', '2.5.0'
mod 'puppetlabs-puppet_agent', '2.0.1'
mod 'puppetlabs-puppet_metrics_collector', '5.1.1'
mod 'puppetlabs-puppet_metrics_dashboard', '1.0.3'
mod 'puppetlabs-stdlib', '5.2.0'
